macro_rules! add_ign_first {
    ($_: expr) => {
        compile_error!("More than one needed")
    };
    ($_: expr, $($z: expr),+) => {{
        add!($($z),*)
    }};
}

macro_rules! add {
    ($x: expr) => ($x);
    ($x: expr, $($z: expr),+) => {{
        $x + add!($($z),*)
    }};
}

macro_rules! decl_consts {
    ($($val:literal),* $(,)?) => {
        (
            add_ign_first!($($val),*),
            &[$($val),*]
        )
    };
}

// First entry is the size of the input!
const _INTERNAL_CONSTANTS : (usize, &[usize]) = decl_consts!(10,64,128,128,128,128,128,128,128,128,256,8);

pub const TOTAL_FF : usize = _INTERNAL_CONSTANTS.0;
pub const U32_NEEDED_FOR_FF : usize = (TOTAL_FF + 31) / 32;
pub const PREVIOUS_STAGE_FF : &[usize] = _INTERNAL_CONSTANTS.1;
pub const OUTPUT_START: usize = TOTAL_FF - PREVIOUS_STAGE_FF[PREVIOUS_STAGE_FF.len() - 1];
pub const TOTAL_MACHINES : usize = 3584 * 2;
pub const U32_PER_STIMULI : usize= (PREVIOUS_STAGE_FF[0] + 31) / 32;
pub const U32_PER_OUTPUT : usize= (PREVIOUS_STAGE_FF[PREVIOUS_STAGE_FF.len() - 1] + 31) / 32;

const SV_ZERO : &'static str = "'0";
const SV_XOR : &'static str = "(a ^ b)";
const SV_AND : &'static str = "(a & b)";
const SV_OR : &'static str = "(a | b)";
const SV_ONE : &'static str = "'1";
const SV_XNOR : &'static str = "~(a ^ b)";
const SV_NAND : &'static str = "~(a & b)";
const SV_NOR : &'static str = "~(a | b)";

const SV_TEMPLATE : &'static str =
r#"// AUTOGENERATED FOR SOCC_ON_CROCC
//Mikail Gedik
//Thomas Herzog
module %MODULE_NAME% #(
)(
    input  logic                 clk_i,
    input  logic                 rst_ni,
    input  logic [%WIDTH_IN%:0] data_i,
    output logic [%WIDTH_OUT%:0] data_o
);
%LOGIC_DECL%
    always_ff @( posedge clk_i, negedge rst_ni ) begin : assign_ffs
%FLIPFLOP%
    end

    always_comb begin
%COMB%
    end
endmodule
"#;

#[derive(Debug, Clone, Copy)]
pub struct Machines {
    pub bitfiddle: [[[u32; 4]; U32_NEEDED_FOR_FF]; TOTAL_MACHINES],
    pub sources: [[u32; U32_NEEDED_FOR_FF * 32]; TOTAL_MACHINES],
}

impl Machines {
    pub fn new() -> Self {
        Self {
            bitfiddle: [[[0u32; 4]; U32_NEEDED_FOR_FF]; TOTAL_MACHINES],
            sources: [[0u32; U32_NEEDED_FOR_FF * 32]; TOTAL_MACHINES],
        }
    }

    pub fn to_sv(&self,
        machine: usize,
        module_name: &str) -> String {

        let bitfiddle: &[[u32; 4]; U32_NEEDED_FOR_FF] = &self.bitfiddle[machine];
        let sources: &[u32; U32_NEEDED_FOR_FF * 32] = &self.sources[machine];

        let logic_decls : String = format!("\tlogic [{TOTAL_FF}-1:0] state_d, state_q;\n");
        let ff_stms : String = "\t\tstate_q <= rst_ni ? state_d : 'b0;\n".into();
        let mut comb_stmts : String = "".into();

        for i in 0..TOTAL_FF {
            let b = i % 32;
            let idx = i / 32;

            let mut bits : u32 = (bitfiddle[idx][2] >> b) & 1;
            bits = (bits << 1) | ((bitfiddle[idx][1] >> b) & 1);
            bits = (bits << 1) | ((bitfiddle[idx][0] >> b) & 1);
            
            let rhs : &str = match bits {
                0b000 => SV_ZERO,
                0b001 => SV_AND,
                0b010 => SV_XOR,
                0b011 => SV_OR,
                0b100 => SV_ONE,
                0b101 => SV_NAND,
                0b110 => SV_XNOR,
                0b111 => SV_NOR,
                _ => panic!("Oh no"),
            };
            let rhs_a;
            let rhs_b;
            if i < PREVIOUS_STAGE_FF[1] {
                rhs_a = format!("data_i[{}]", &(sources[i] & 0xFFFF).to_string());
                rhs_b = format!("data_i[{}]", &((sources[i] >> 16) & 0xFFFF).to_string());
            } else {
                rhs_a = format!("state_q[{}]", &(sources[i] & 0xFFFF).to_string());
                rhs_b = format!("state_q[{}]", &((sources[i] >> 16) & 0xFFFF).to_string());
            }
            comb_stmts += &format!("\t\tstate_d[{i}] = ");
            comb_stmts += &rhs.replace("a", &rhs_a).replace("b", &rhs_b);
            comb_stmts += ";\n";
        }

        let out_start_ff : usize = PREVIOUS_STAGE_FF[1..PREVIOUS_STAGE_FF.len() - 1].iter().fold(0, |a,b| a + b );
        let out_end_ff : usize = out_start_ff + PREVIOUS_STAGE_FF[PREVIOUS_STAGE_FF.len() - 1];
        comb_stmts += &format!("\t\tdata_o = state_q[{out_end_ff}-1:{out_start_ff}];");

        return SV_TEMPLATE.replace(
            "%MODULE_NAME%", &module_name).replace(
            "%WIDTH_IN%", &(PREVIOUS_STAGE_FF[0] - 1).to_string()).replace(
            "%WIDTH_OUT%", &(PREVIOUS_STAGE_FF[PREVIOUS_STAGE_FF.len() - 1] - 1).to_string()).replace(
            "%LOGIC_DECL%", &logic_decls).replace(
            "%COMB%", &comb_stmts).replace(
            "%FLIPFLOP%", &ff_stms);
    }
}
