use rand::{Rng, SeedableRng};
use rand::RngExt;
use rand::rngs::StdRng;

use std::cmp::min;

macro_rules! max {
    ($x: expr) => ($x);
    ($x: expr, $($z: expr),+) => {{
        let y = max!($($z),*);
        if $x > y {
            $x
        } else {
            y
        }
    }};
}

macro_rules! decl_consts {
    ($($val:literal),* $(,)?) => {
        (
        &[$(($val + 31) / 32),*],
        &[$($val),*],
        (max!($($val),*) + 31) / 32
    )
    };
}

// First stage is a "dummy" stage for the input!
const _NO_CONSTS : (&[usize], &[usize], usize) = decl_consts!(32,4096,32);

pub const U32_PER_STAGE: &[usize] = _NO_CONSTS.0;
pub const FF_PER_STAGE: &[usize] = _NO_CONSTS.1;
pub const U32_MAX_PER_STAGE: usize = _NO_CONSTS.2;

const SV_ZERO : &'static str = "'0";
const SV_XOR : &'static str = "(a ^ b)";
const SV_AND : &'static str = "(a & b)";
const SV_OR : &'static str = "(a | b)";
const SV_ONE : &'static str = "'1";
const SV_XNOR : &'static str = "~(a ^ b)";
const SV_NAND : &'static str = "~(a & b)";
const SV_NOR : &'static str = "~(a | b)";

const SV_TEMPLATE : &'static str =
r#"// AUTOGENERATED FOR SOCC_ON_CROCC
//Mikail Gedik
//Thomas Herzog
module %MODULE_NAME% #(
)(
    input  logic                 clk_i,
    input  logic                 rst_ni,
    input  logic [%WIDTH_IN%:0] data_i,
    output logic [%WIDTH_OUT%:0] data_o
);
%LOGIC_DECL%
    always_ff @( posedge clk_i, negedge rst_ni ) begin : assign_ffs
%FLIPFLOP%
    end

    always_comb begin
%COMB%
    end
endmodule
"#;

pub fn vec_from_arrs<'a, T : Iterator<Item = &'a [u32;SIZE]>, const SIZE: usize>(iter: T) -> Vec<u8> {
    let mut r = Vec::new();
    for i in iter {
        for j in i {
            r.extend(j.to_le_bytes());
        }
    }
    r
}

pub fn vec_from_arrs_u16<'a, T : Iterator<Item = &'a [(u16, u16);SIZE]>, const SIZE: usize>(iter: T) -> Vec<u8> {
    let mut r = Vec::new();
    for i in iter {
        for (j1,j2) in i {
            r.extend((*j1 as u32 | ((*j2 as u32) << 16)).to_le_bytes());
        }
    }
    r
}

#[derive(Debug, Clone, Copy)]
pub struct StageComb {
    gates: usize,
    sources: [(u16,u16); U32_MAX_PER_STAGE * 32],
    and_enable: [u32; U32_MAX_PER_STAGE],
    xor_enable: [u32; U32_MAX_PER_STAGE],
    inv_enable: [u32; U32_MAX_PER_STAGE],
}

#[derive(Debug, Clone, Copy)]
pub struct Machine {
    comb: [StageComb; U32_PER_STAGE.len()],
    // stage_q: [[u32; U32_MAX_PER_STAGE]; U32_PER_STAGE.len()],
}


impl StageComb {
    pub fn new(gates: usize) -> Self {
        assert!(U32_MAX_PER_STAGE * 32 >= gates);
        StageComb{
            gates: gates,
            sources: [(0,0); U32_MAX_PER_STAGE * 32],
            and_enable: [0; U32_MAX_PER_STAGE],
            xor_enable: [0; U32_MAX_PER_STAGE],
            inv_enable: [0; U32_MAX_PER_STAGE]
        }
    }

    // pub fn calc_next_stage(&self, input: &[u32], dst: &mut [u32]) {
    //     let stage_u32 = (self.gates + 31) / 32;
    //     assert!(stage_u32 <= dst.len());
    //     for i in 0..stage_u32 {
    //         let mut src_a : u32 = 0;
    //         let mut src_b : u32 = 0;
    //         for (idx_a, idx_b) in &self.sources[(32 * i)..(32 * (i+1))] {
    //             src_a <<= 1;
    //             src_b <<= 1;
    //             src_a |= (input[(*idx_a / 32) as usize] >> ((*idx_a as usize) % 32)) & 1;
    //             src_b |= (input[(*idx_b / 32) as usize] >> ((*idx_b as usize) % 32)) & 1;
    //         }
    //         dst[i] = (((src_a & src_b) & self.and_enable[i]) | ((src_a ^ src_b) & self.xor_enable[i])) ^ self.inv_enable[i];
    //     }
    // }

    pub fn to_sv_rhs(&self) -> Vec<&'static str> {
        fn tuple_to_sv_rhs(mut and_xor_inv: (u32, u32, u32)) -> [&'static str; 32] {
            let mut r = [""; 32];
            for i in 0..32 {
                r[i] = match ((and_xor_inv.1 & 1) << 0) | ((and_xor_inv.0 & 1) << 1) | ((and_xor_inv.2 & 1) << 2) {
                    0b000 => SV_ZERO,
                    0b001 => SV_XOR,
                    0b010 => SV_AND,
                    0b011 => SV_OR,
                    0b100 => SV_ONE,
                    0b101 => SV_XNOR,
                    0b110 => SV_NAND,
                    0b111 => SV_NOR,
                    _ => panic!("Oh no"),
                };

                and_xor_inv.0 >>= 1;
                and_xor_inv.1 >>= 1;
                and_xor_inv.2 >>= 1;
            }
            r
        }
        let mut r = Vec::with_capacity(self.gates);
        for i in 0..(self.gates.div_ceil(32)) {
            let v = tuple_to_sv_rhs((self.and_enable[i], self.xor_enable[i], self.inv_enable[i]));
            let end = min(self.gates, (i + 1) * 32) - i * 32;
            r.extend(&v[0..end]);
        }
        r
    }
}

impl Machine {
    pub fn new() -> Self {
        Machine {
            comb: FF_PER_STAGE.iter().map(|u| {
                StageComb::new(*u)
            }).collect::<Vec<StageComb>>().try_into().expect("Very very bad"),
            // stage_q: [[0u32; U32_MAX_PER_STAGE]; U32_PER_STAGE.len()]
        }
    }

    pub fn rng(&mut self, seed: u32) {
        let mut s = [0u8; 32];
        for i in 0..4 {
            s[i] = seed.to_le_bytes()[i];
        }
        let mut rng = StdRng::from_seed(s);

        for i in 1..U32_PER_STAGE.len() {
            let prev_gates = self.comb[i-1].gates as u16;
            let c = &mut self.comb[i];

            for u in 0..c.gates {
                let r = rng.next_u32();
                let mut s1 : u16 = (r & 0xFFFF) as u16;
                let mut s2 : u16 = ((r >> 16) & 0xFFFF) as u16;
                s1 %= prev_gates;
                s2 %= prev_gates;
                
                c.sources[u] = (s1, s2);
            }
            rng.fill(&mut c.and_enable);
            rng.fill(&mut c.xor_enable);
            rng.fill(&mut c.inv_enable);
        }
    }

    // pub fn run(&mut self, stimuli: Vec<[u32; U32_MAX_PER_STAGE]>) -> Vec<[u32; U32_MAX_PER_STAGE]> {
    //     let mut r = Vec::with_capacity(stimuli.len());
    //     for s in stimuli {
    //         self.stage_q[0] = s;
    //         // Purposefully leave out 0, it is a dummy stage for the input
    //         for i in (self.comb.len() - 1)..0 {
    //             let (lower, higher) = self.stage_q.split_at_mut(i);
    //             self.comb[i].calc_next_stage(&lower[lower.len() - 1], &mut higher[0]);
    //         }
    //         r.push(self.stage_q[self.stage_q.len() - 1]);
    //     }
    //     r
    // }

    pub fn get_sources(&self) -> Vec<u8> {
        vec_from_arrs_u16(self.comb.iter().skip(1).map(|i| &i.sources))
    }

    pub fn get_and(&self) -> Vec<u8> {
        vec_from_arrs(self.comb.iter().skip(1).map(|i| &i.and_enable))
    }
    pub fn get_xor(&self) -> Vec<u8> {
        vec_from_arrs(self.comb.iter().skip(1).map(|i| &i.xor_enable))
    }
    pub fn get_inv(&self) -> Vec<u8> {
        vec_from_arrs(self.comb.iter().skip(1).map(|i| &i.inv_enable))
    }


    pub fn to_sv(&self, module_name: &str) -> String {
        let mut logic_decls : String = "".into();
        let mut comb_stmts : String= "".into();
        let mut ff_stms : String= "".into();
        let mut prev_stage_q : String = "data_i".to_string();

        // skip first stage. First stage is for input only
        for i in 1..self.comb.len() {
            let stage = &self.comb[i];
            let stage_amount = stage.gates - 1;
            logic_decls += &format!("\tlogic [{stage_amount}:0] state_{i}_d, state_{i}_q;\n");
            ff_stms += &format!("\t\tstate_{i}_q <= rst_ni ? state_{i}_d : 'b0;\n");

            let stage_rhs : Vec<&'static str> = stage.to_sv_rhs();
            for ii in 0..stage_rhs.len() {
                let (src_a, src_b) = (stage.sources[ii].0, stage.sources[ii].1);
                let rhs_a = &format!("{prev_stage_q}[{src_a}]");
                let rhs_b = &format!("{prev_stage_q}[{src_b}]");
                let rhs = stage_rhs[ii].replace("a", rhs_a).replace("b", rhs_b);
                comb_stmts += &format!("\t\tstate_{i}_d[{ii}] = {rhs};\n");
            }
                
            prev_stage_q = format!("state_{i}_q");
        
        }

        let out_length = self.comb.len() - 1;
        comb_stmts += &format!("\t\tdata_o = state_{out_length}_q;");
        return SV_TEMPLATE.replace(
            "%MODULE_NAME%", &module_name).replace(
            "%WIDTH_IN%", &(FF_PER_STAGE[0] - 1).to_string()).replace(
            "%WIDTH_OUT%", &(FF_PER_STAGE[FF_PER_STAGE.len() - 1] - 1).to_string()).replace(
            "%LOGIC_DECL%", &logic_decls).replace(
            "%COMB%", &comb_stmts).replace(
            "%FLIPFLOP%", &ff_stms);
    }
}
