#!/usr/bin/env python3
import sys
import os
"""
Generates binary data for the OBI requests
"""

RAM_ADDR_WIDTH = 10 + 2

class ObiR:
    def __init__(self, addr: int, data: int, we: bool, mask: int = 0b1111):
        self.addr = addr
        self.data = data
        self.attr = (mask << 28)
        self.attr |= (1 if we else 0)

reqs : list[ObiR] = [
    ObiR(0x0, 0x04030201, True),
    ObiR(0x0, 0x04030201, False),
    ObiR(0x0 + (1 << RAM_ADDR_WIDTH) * 1, 0xfeeffaaf, True),
    ObiR(0x0 + (1 << RAM_ADDR_WIDTH) * 1, 0x0, False),
    ObiR(0x0 + (1 << RAM_ADDR_WIDTH) * 2, 0xfaaff00f, True),
    ObiR(0x0 + (1 << RAM_ADDR_WIDTH) * 2, 0x0, False),
]

for i in range(128):
    reqs.append(ObiR(4*i + (1 << RAM_ADDR_WIDTH) * 1, (2 * i) | ((2 * i + 1) << 16), True))

FILE_CONTENT = """
// Copyright 2026 ETH Zurich.
// Solderpad Hardware License, Version 0.51, see LICENSE for details.
// SPDX-License-Identifier: SHL-0.51
//
// Mikail Gedik <mgedik@student.ethz.ch>
//
// AUTOMATICALLY GENERATED by %SCRIPT_NAME%; edit the script instead.
`ifndef SOCC_OBI_REQUEST_HELPER
`define SOCC_OBI_REQUEST_HELPER 1

typedef struct packed {
    int addr;
    int value;
    int attr;
} obi_orders_t;

function obi_orders_t get_obi_order(logic [31:0] idx);
    case(idx)
        %OBI_REQS%;
    endcase
endfunction

localparam MAX_OBI_ORDERS = %OBI_REQS_LEN%;

`endif // SOCC_OBI_REQUEST_HELPER
"""

if __name__ == '__main__':
    if len(sys.argv) != 2:
        raise ValueError("to many/few args. only provide output file")

    replacment = ";\n\t\t".join(list(map(
        lambda l: f"'d{l[0]}: get_obi_order = {{32'd{l[1].addr}, 32'd{l[1].data}, 32'd{l[1].attr}}}",
        zip(range(len(reqs)),reqs))))
    res = FILE_CONTENT.replace("%OBI_REQS%", replacment).replace("%OBI_REQS_LEN%", str(len(reqs))).replace("%SCRIPT_NAME%", os.path.basename(__file__))

    with open(sys.argv[1], "w") as f:
        f.write(res)