#!/usr/bin/env python3
import sys
import os
import random
"""
Generates binary data for the OBI requests
"""

RAM_ADDR_WIDTH = 11 + 2

BASE_ADDR_TEXT = (1 << RAM_ADDR_WIDTH)
BASE_ADDR_GLYPH = (1 << RAM_ADDR_WIDTH) * 2


class ObiR:
    def __init__(self, addr: int, data: int, we: bool, mask: int = 0b1111, check_read : bool = False):
        self.addr = addr
        self.data = data
        self.attr = (mask << 28)
        self.attr |= (1 if check_read else 0) << 27
        self.attr |= (1 if we else 0)


reqs : list[ObiR] = [
    ObiR(0x0, 0xfeeffaaf, True),
    ObiR(0x0, 0xfeeffaaf, False, check_read=True),
    ObiR(0x4, 0xaaaaaaaa, True),
    ObiR(0x4, 0xbbbbbbbb, True, mask=0b0010),
    ObiR(0x4, 0xaaaabbaa, False, check_read=True),

    ObiR(0x0 + BASE_ADDR_TEXT, 0xfeeffaaf, True),
    ObiR(0x0 + BASE_ADDR_TEXT, 0xfeeffaaf, False, check_read=True),
    ObiR(0x4 + BASE_ADDR_TEXT, 0xaaaaaaaa, True),
    ObiR(0x4 + BASE_ADDR_TEXT, 0xbbbbbbbb, True, mask=0b0010),
    ObiR(0x4 + BASE_ADDR_TEXT, 0xaaaabbaa, False, check_read=True),

    # Test read/write capabilities
    ObiR(0x0 + BASE_ADDR_GLYPH, 0xeffeaffe, True),
    ObiR(0x0 + BASE_ADDR_GLYPH, 0xeffeaffe, False, check_read=True),
    ObiR(0x4 + BASE_ADDR_GLYPH, 0x11111111, True),
    ObiR(0x4 + BASE_ADDR_GLYPH, 0x22222222, True, mask=0b0010),
    ObiR(0x4 + BASE_ADDR_GLYPH, 0x11112211, False, check_read=True),
]

r = random.Random(0)
for row in range(30):
    for col in range(80):
        i = 80 * row + col
        # bg_col_idx = r.randrange(8) & 0b111
        # fg_col_idx = r.randrange(16) & 0b1111
        # c = ((bg_col_idx & 0b111) << 4) | (fg_col_idx & 0b1111)
        # print("Bg: ", bg_col_idx, "Fg: ", fg_col_idx)
        # c = c << 8
        # c |= i % 256
        c = i % 256
        c = c | ((i % 256) << 8)
        # if row == 0:
        #     c = i % 256
        # if row == 24:
        #     c = (0xffff - i) % 256
        if col == 0:
            c = ((row % 10) + ord('0')) | (0b00001111 << 8)
        reqs.append(ObiR(4*(i//2) + BASE_ADDR_TEXT, c if i % 2 == 0 else (c << 16), True, mask=(0b0011 if i%2 == 0 else 0b1100)))

with open("../res/font/raw.bin", "rb") as f:
    data = f.read()
    assert len(data) % 4 == 0
    for i in range(len(data) // 4):
        word = 0
        if i // 4 >= ord('A') and i // 4 <= ord('z') or i // 4 >= ord('0') and i // 4 <= ord('9'):
            word = int.from_bytes(data[4*i:4*i+4], byteorder='little')
        reqs.append(ObiR(4*i + BASE_ADDR_GLYPH, word, True))

# Write back default colors after testing regs
reqs.append(ObiR(0x00, 0x00110000, True))
reqs.append(ObiR(0x04, 0x04510320, True))
reqs.append(ObiR(0x08, 0x88118800, True))
reqs.append(ObiR(0x0C, 0x8410a145, True))
reqs.append(ObiR(0x10, 0x001fd69a, True))
reqs.append(ObiR(0x14, 0x07ff0400, True))
reqs.append(ObiR(0x18, 0xf81ff800, True))
reqs.append(ObiR(0x1C, 0xffffffe0, True))


reqs.append(ObiR(0x20, 0b0000_0010_0000_0000_1100_0000, True))

FILE_CONTENT = """
// Copyright 2026 ETH Zurich.
// Solderpad Hardware License, Version 0.51, see LICENSE for details.
// SPDX-License-Identifier: SHL-0.51
//
// Mikail Gedik <mgedik@student.ethz.ch>
//
// AUTOMATICALLY GENERATED by %SCRIPT_NAME%; edit the script instead.
`ifndef SOCC_OBI_REQUEST_HELPER
`define SOCC_OBI_REQUEST_HELPER 1

typedef struct packed {
    int addr;
    int value;
    int attr;
} obi_orders_t;

function obi_orders_t get_obi_order(logic [31:0] idx);
    case(idx)
        %OBI_REQS%;
    endcase
endfunction

localparam MAX_OBI_ORDERS = %OBI_REQS_LEN%;

`endif // SOCC_OBI_REQUEST_HELPER
"""

if __name__ == '__main__':
    if len(sys.argv) != 2:
        raise ValueError("to many/few args. only provide output file")

    replacment = ";\n\t\t".join(list(map(
        lambda l: f"'d{l[0]}: get_obi_order = {{32'd{l[1].addr}, 32'd{l[1].data}, 32'd{l[1].attr}}}",
        zip(range(len(reqs)),reqs))))
    res = FILE_CONTENT.replace("%OBI_REQS%", replacment).replace("%OBI_REQS_LEN%", str(len(reqs))).replace("%SCRIPT_NAME%", os.path.basename(__file__))

    with open(sys.argv[1], "w") as f:
        f.write(res)